plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-youtube

# SEO Stuff
author: Terrance Brown
description: A simple site, based on Simple.css
lang: en
locale: en_GB
url: "https://terrancebrown.github.io"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20
